variable "organization" {
  type = string
}

variable "stage" {
  type = string
}

variable "aws_user" {
  type = string
  default = "ec2-user"
}

variable "ssh_port" {
  type = number
  default = 12202
}

variable "aws_subnet_public_a" {
  type = string
}

variable "vpc_id" {
  type = string
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
