variable "subnet_id" {
  type = string
}

variable "vpc_id" {
  type = string
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "tags" {
  type = map(string)
  default = {
    name: "bastion"
  }
  description = "tags"
}
